import type { FoodPayload } from "../../repositories/foodRepository";

export const DEFAULT_FOODS: FoodPayload[] = [
  {
    name: "Arroz branco cozido",
    category: "carboidrato",
    servingSize: 100,
    servingUnit: "g",
    calories: 128,
    protein: 2.5,
    carbs: 28.1,
    fat: 0.2,
    fiber: 1.6,
    sodium: 1,
    source: "manual-seed",
  },
  {
    name: "Feijao carioca cozido",
    category: "leguminosa",
    servingSize: 100,
    servingUnit: "g",
    calories: 76,
    protein: 4.8,
    carbs: 13.6,
    fat: 0.5,
    fiber: 8.5,
    sodium: 2,
    source: "manual-seed",
  },
  {
    name: "Peito de frango grelhado",
    category: "proteina",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sodium: 74,
    source: "manual-seed",
  },
  {
    name: "Ovo de galinha cozido",
    category: "proteina",
    servingSize: 50,
    servingUnit: "g",
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    sodium: 62,
    source: "manual-seed",
  },
  {
    name: "Batata doce cozida",
    category: "carboidrato",
    servingSize: 100,
    servingUnit: "g",
    calories: 77,
    protein: 0.6,
    carbs: 18.4,
    fat: 0.1,
    fiber: 2.2,
    sodium: 3,
    source: "manual-seed",
  },
  {
    name: "Aveia em flocos",
    category: "cereal",
    servingSize: 30,
    servingUnit: "g",
    calories: 114,
    protein: 4.2,
    carbs: 20.1,
    fat: 2.5,
    fiber: 2.7,
    sodium: 1,
    source: "manual-seed",
  },
  {
    name: "Banana prata",
    category: "fruta",
    servingSize: 100,
    servingUnit: "g",
    calories: 89,
    protein: 1.3,
    carbs: 23.8,
    fat: 0.1,
    fiber: 2,
    sodium: 0,
    source: "manual-seed",
  },
  {
    name: "Brocolis cozido",
    category: "vegetal",
    servingSize: 100,
    servingUnit: "g",
    calories: 25,
    protein: 2.1,
    carbs: 4.4,
    fat: 0.5,
    fiber: 3.4,
    sodium: 2,
    source: "manual-seed",
  },
  {
    name: "Azeite de oliva",
    category: "gordura",
    servingSize: 13,
    servingUnit: "ml",
    calories: 108,
    protein: 0,
    carbs: 0,
    fat: 12,
    fiber: 0,
    sodium: 0,
    source: "manual-seed",
  },
  {
    name: "Iogurte natural integral",
    category: "laticinio",
    servingSize: 170,
    servingUnit: "g",
    calories: 104,
    protein: 6.8,
    carbs: 8.8,
    fat: 5.1,
    fiber: 0,
    sodium: 80,
    source: "manual-seed",
  },
];
